#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.19132
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Store")]
public partial class ShowUserDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertMobilePhone(MobilePhone instance);
  partial void UpdateMobilePhone(MobilePhone instance);
  partial void DeleteMobilePhone(MobilePhone instance);
  partial void InsertPhoneModel(PhoneModel instance);
  partial void UpdatePhoneModel(PhoneModel instance);
  partial void DeletePhoneModel(PhoneModel instance);
  partial void InsertSeller(Seller instance);
  partial void UpdateSeller(Seller instance);
  partial void DeleteSeller(Seller instance);
  #endregion
	
	public ShowUserDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["StoreConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public ShowUserDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ShowUserDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ShowUserDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ShowUserDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<MobilePhone> MobilePhones
	{
		get
		{
			return this.GetTable<MobilePhone>();
		}
	}
	
	public System.Data.Linq.Table<PhoneModel> PhoneModels
	{
		get
		{
			return this.GetTable<PhoneModel>();
		}
	}
	
	public System.Data.Linq.Table<Seller> Sellers
	{
		get
		{
			return this.GetTable<Seller>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MobilePhones")]
public partial class MobilePhone : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Name;
	
	private EntitySet<PhoneModel> _PhoneModels;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
	
	public MobilePhone()
	{
		this._PhoneModels = new EntitySet<PhoneModel>(new Action<PhoneModel>(this.attach_PhoneModels), new Action<PhoneModel>(this.detach_PhoneModels));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MobilePhone_PhoneModel", Storage="_PhoneModels", ThisKey="Id", OtherKey="Name_Id")]
	public EntitySet<PhoneModel> PhoneModels
	{
		get
		{
			return this._PhoneModels;
		}
		set
		{
			this._PhoneModels.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_PhoneModels(PhoneModel entity)
	{
		this.SendPropertyChanging();
		entity.MobilePhone = this;
	}
	
	private void detach_PhoneModels(PhoneModel entity)
	{
		this.SendPropertyChanging();
		entity.MobilePhone = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhoneModel")]
public partial class PhoneModel : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Model;
	
	private System.Nullable<decimal> _Camera;
	
	private decimal _Capacity;
	
	private System.Nullable<decimal> _CPU;
	
	private System.Nullable<decimal> _Ram;
	
	private string _BigImage;
	
	private string _SmallImage;
	
	private string _AllImage;
	
	private decimal _Price;
	
	private string _MoreInformation;
	
	private bool _onHand;
	
	private int _Name_Id;
	
	private EntityRef<MobilePhone> _MobilePhone;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnModelChanging(string value);
    partial void OnModelChanged();
    partial void OnCameraChanging(System.Nullable<decimal> value);
    partial void OnCameraChanged();
    partial void OnCapacityChanging(decimal value);
    partial void OnCapacityChanged();
    partial void OnCPUChanging(System.Nullable<decimal> value);
    partial void OnCPUChanged();
    partial void OnRamChanging(System.Nullable<decimal> value);
    partial void OnRamChanged();
    partial void OnBigImageChanging(string value);
    partial void OnBigImageChanged();
    partial void OnSmallImageChanging(string value);
    partial void OnSmallImageChanged();
    partial void OnAllImageChanging(string value);
    partial void OnAllImageChanged();
    partial void OnPriceChanging(decimal value);
    partial void OnPriceChanged();
    partial void OnMoreInformationChanging(string value);
    partial void OnMoreInformationChanged();
    partial void OnonHandChanging(bool value);
    partial void OnonHandChanged();
    partial void OnName_IdChanging(int value);
    partial void OnName_IdChanged();
    #endregion
	
	public PhoneModel()
	{
		this._MobilePhone = default(EntityRef<MobilePhone>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Model
	{
		get
		{
			return this._Model;
		}
		set
		{
			if ((this._Model != value))
			{
				this.OnModelChanging(value);
				this.SendPropertyChanging();
				this._Model = value;
				this.SendPropertyChanged("Model");
				this.OnModelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Camera", DbType="Decimal(4,2)")]
	public System.Nullable<decimal> Camera
	{
		get
		{
			return this._Camera;
		}
		set
		{
			if ((this._Camera != value))
			{
				this.OnCameraChanging(value);
				this.SendPropertyChanging();
				this._Camera = value;
				this.SendPropertyChanged("Camera");
				this.OnCameraChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacity", DbType="Decimal(6,2) NOT NULL")]
	public decimal Capacity
	{
		get
		{
			return this._Capacity;
		}
		set
		{
			if ((this._Capacity != value))
			{
				this.OnCapacityChanging(value);
				this.SendPropertyChanging();
				this._Capacity = value;
				this.SendPropertyChanged("Capacity");
				this.OnCapacityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPU", DbType="Decimal(6,2)")]
	public System.Nullable<decimal> CPU
	{
		get
		{
			return this._CPU;
		}
		set
		{
			if ((this._CPU != value))
			{
				this.OnCPUChanging(value);
				this.SendPropertyChanging();
				this._CPU = value;
				this.SendPropertyChanged("CPU");
				this.OnCPUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ram", DbType="Decimal(6,2)")]
	public System.Nullable<decimal> Ram
	{
		get
		{
			return this._Ram;
		}
		set
		{
			if ((this._Ram != value))
			{
				this.OnRamChanging(value);
				this.SendPropertyChanging();
				this._Ram = value;
				this.SendPropertyChanged("Ram");
				this.OnRamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BigImage", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string BigImage
	{
		get
		{
			return this._BigImage;
		}
		set
		{
			if ((this._BigImage != value))
			{
				this.OnBigImageChanging(value);
				this.SendPropertyChanging();
				this._BigImage = value;
				this.SendPropertyChanged("BigImage");
				this.OnBigImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmallImage", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string SmallImage
	{
		get
		{
			return this._SmallImage;
		}
		set
		{
			if ((this._SmallImage != value))
			{
				this.OnSmallImageChanging(value);
				this.SendPropertyChanging();
				this._SmallImage = value;
				this.SendPropertyChanged("SmallImage");
				this.OnSmallImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllImage", DbType="VarChar(500)")]
	public string AllImage
	{
		get
		{
			return this._AllImage;
		}
		set
		{
			if ((this._AllImage != value))
			{
				this.OnAllImageChanging(value);
				this.SendPropertyChanging();
				this._AllImage = value;
				this.SendPropertyChanged("AllImage");
				this.OnAllImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(10,2) NOT NULL")]
	public decimal Price
	{
		get
		{
			return this._Price;
		}
		set
		{
			if ((this._Price != value))
			{
				this.OnPriceChanging(value);
				this.SendPropertyChanging();
				this._Price = value;
				this.SendPropertyChanged("Price");
				this.OnPriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoreInformation", DbType="VarChar(800)")]
	public string MoreInformation
	{
		get
		{
			return this._MoreInformation;
		}
		set
		{
			if ((this._MoreInformation != value))
			{
				this.OnMoreInformationChanging(value);
				this.SendPropertyChanging();
				this._MoreInformation = value;
				this.SendPropertyChanged("MoreInformation");
				this.OnMoreInformationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_onHand", DbType="Bit NOT NULL")]
	public bool onHand
	{
		get
		{
			return this._onHand;
		}
		set
		{
			if ((this._onHand != value))
			{
				this.OnonHandChanging(value);
				this.SendPropertyChanging();
				this._onHand = value;
				this.SendPropertyChanged("onHand");
				this.OnonHandChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name_Id", DbType="Int NOT NULL")]
	public int Name_Id
	{
		get
		{
			return this._Name_Id;
		}
		set
		{
			if ((this._Name_Id != value))
			{
				if (this._MobilePhone.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnName_IdChanging(value);
				this.SendPropertyChanging();
				this._Name_Id = value;
				this.SendPropertyChanged("Name_Id");
				this.OnName_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MobilePhone_PhoneModel", Storage="_MobilePhone", ThisKey="Name_Id", OtherKey="Id", IsForeignKey=true)]
	public MobilePhone MobilePhone
	{
		get
		{
			return this._MobilePhone.Entity;
		}
		set
		{
			MobilePhone previousValue = this._MobilePhone.Entity;
			if (((previousValue != value) 
						|| (this._MobilePhone.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._MobilePhone.Entity = null;
					previousValue.PhoneModels.Remove(this);
				}
				this._MobilePhone.Entity = value;
				if ((value != null))
				{
					value.PhoneModels.Add(this);
					this._Name_Id = value.Id;
				}
				else
				{
					this._Name_Id = default(int);
				}
				this.SendPropertyChanged("MobilePhone");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Seller")]
public partial class Seller : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _FirstName;
	
	private string _LastName;
	
	private string _Login;
	
	private string _Password;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
	
	public Seller()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this.OnFirstNameChanging(value);
				this.SendPropertyChanging();
				this._FirstName = value;
				this.SendPropertyChanged("FirstName");
				this.OnFirstNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this.OnLastNameChanging(value);
				this.SendPropertyChanging();
				this._LastName = value;
				this.SendPropertyChanged("LastName");
				this.OnLastNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Login
	{
		get
		{
			return this._Login;
		}
		set
		{
			if ((this._Login != value))
			{
				this.OnLoginChanging(value);
				this.SendPropertyChanging();
				this._Login = value;
				this.SendPropertyChanged("Login");
				this.OnLoginChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
